### ISSUE TITLE
Vector inputs

### ISSUE THREAD

**Issue by leuchine** [ahmedmalaa/Symbolic-Metamodeling#1]
Hi Ahmed:

Thanks a lot for sharing the code! At the moment, the parameterization focuses on taking a vector as the input and outputting a single score. May I ask is it possible for the metamodelling to take multiple vectors as the input, e.g. given a set of vectors, output a score or a single vector? Thanks!

Best Regards,
Qi

**Comment by ahmedmalaa** [comment]
Hi Qi,

The current implementation takes a multidimensional feature input (a vector) and maps it to a scalar output. Unfortunately, right now neither the implementation nor the formulation itself support multidimensional outputs. We will consider adding this feature in future releases.

Thanks!

**Comment by leuchine** [comment]
Hi Ahmed:

Thanks for the reply! I don't know whether there are easy to extend the G function for the vector input.  I think one straightforward way is doing an elementwise operation? Thanks!

Best Regards,
Qi

**Comment by leuchine** [comment]
Hi Ahmed:

I read the code. The gradients during backpropagation seem a bit confusing to me. May I ask what's the formula for the basis_grad in the file symbolic_metamodeling.py. Also, the gradients function in the file special_functions.py does not match the formula (6) in the paper? I maybe understand wrongly here. Please correct me if that's the case. Thanks!

Best Regards,
Qi

**Comment by ahmedmalaa** [comment]
Hi Qi:

The general approximate formula for the gradients is quite unstable and the integral may not converge for some values of the poles during the SGD iterations. What we implemented in this version is an approximate gradient formula for a Meijer G function G^{1,3}_{0,1} with specific number of poles because for this one we could find a general analytic approximation that is stable for any values of the poles. In the next release, we will provide a stable approximation for the gradient of any G function.

Thanks.
